# Generated by Django 3.0.4 on 2020-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
