# Generated by Django 3.0.4 on 2020-03-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200323_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
